# Generated by Django 5.0.2 on 2024-04-16 23:38

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clothing_type', models.CharField(choices=[('HAT', 'Hat'), ('SHR', 'Shirts and Jackets'), ('PNT', 'Pants'), ('SHO', 'Shoes'), ('MIS', 'Miscellaneous')], max_length=3)),
                ('comfort_low', models.IntegerField()),
                ('comfort_high', models.IntegerField()),
                ('waterproof_rating', models.IntegerField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='generic_clothes')),
                ('photo', models.ImageField(upload_to='inventory/photos/')),
                ('image_url', models.CharField(blank='True', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('temperature_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='weather_images')),
                ('date', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.location')),
            ],
        ),
    ]
