# Generated by Django 4.2.11 on 2024-04-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericclothes',
            name='image_url',
            field=models.CharField(blank='True', max_length=500),
        ),
        migrations.AlterField(
            model_name='genericclothes',
            name='photo',
            field=models.ImageField(upload_to='inventory/photos/'),
        ),
    ]
