# Generated by Django 5.0.2 on 2024-03-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clothing_type', models.CharField(choices=[('HAT', 'Hat'), ('SHR', 'Shirts and Jackets'), ('PNT', 'Pants'), ('SHO', 'Shoes'), ('MIS', 'Miscellaneous')], max_length=3)),
                ('comfort_low', models.IntegerField()),
                ('comfort_high', models.IntegerField()),
                ('waterproof_rating', models.IntegerField()),
            ],
        ),
    ]
