# Generated by Django 5.0.2 on 2024-04-06 18:24

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_genericclothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericclothes',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='media/generic_clothes'),
        ),
    ]
